included:
  - WristArcana
  - WristArcanaTests

excluded:
  - Pods
  - WristArcana/Resources
  - WristArcana/Preview Content
  
disabled_rules:
  - trailing_whitespace
  - opening_brace
  
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_whitespace_closing_braces
  
line_length: 120
function_body_length: 50
type_body_length: 300
file_length: 500

identifier_name:
  min_length: 2
  max_length: 50
  
cyclomatic_complexity:
  warning: 10
  error: 15
